Feature/simple interest calculator
MIT-Emerging-Talent/ET6-foundations-group-11 pull request #3
Opened 2024-12-28 21:49 UTC by Mustafa-Mangal

---
name: Solution Review 
about: A template PR for code review with a checklist
---

## Simple Interest Calculator: Code Review

### Challenge Solved:
This PR implements the solution for the simple interest calculator coding challenge. The task is to calculate simple interest based on principal, interest rate, and time in years using the formula:

## Simple Interest Formula

The formula for calculating simple interest is:
**I** = _`P × R × T / 100`_
Where:
- \( I \) is the interest
- \( P \) is the principal amount
- \( R \) is the rate of interest per period
- \( T \) is the time the money is invested or borrowed for, in periods

### Changes Implemented:
- Implemented the simple interest calculation logic in `simple_interest_calculator.py`.
- Added unit tests to validate the calculator’s functionality in `test_simple_interest_calculator.py`.

### Behavior

#### Files

- [ ] The file name (`simple_interest_calculator.py`) describes the function's behavior.
- [ ] The test file is named `test_simple_interest_calculator.py` and matches the function file.
- [ ] Both files contain module-level docstrings.

#### Unit Tests

- [ ] The test class is named `TestSimpleInterestCalculator` (PascalCase).
- [ ] The test class includes a docstring.
- [ ] Each test case has a descriptive name and clear docstrings.
- [ ] All tests pass successfully.
- [ ] Tests cover defensive assertions and boundary cases.

#### Function Docstring

- [ ] The function's behavior is well-described in the docstring.
- [ ] Function arguments and return values are clearly documented, including types and assumptions.
- [ ] Proper defensive assertions are included, and they are well-documented.

### Strategy

#### Do's

- [ ] Variable names such as `principal`, `rate`, and `time` are clear and descriptive.
- [ ] The code is organized, and the logic is straightforward, ensuring simplicity.

#### Don'ts

- [ ] No unnecessary comments that explain the implementation; the code is self-explanatory.

### Implementation

- [ ] The code passes formatting and linting checks.
- [ ] No significant Pylint errors.
- [ ] Variables follow snake_case conventions.
- [ ] The code implements the solution in a simple and clean manner.

---

### Review Checklist for Merge:

- [ ] Code passes all tests
- [ ] Linting and formatting checks passed
- [ ] Code reviewed by team member(s)
- [ ] PR linked to corresponding issue on project board

2024-12-29 13:43 UTC, Elocodes commented
Regarding the checks that are not passing, I suggest you format your file with either the ruff or black formatter. Have you tried this?

Secondly, seems like you created extra folders (src and tests) for your challenge. This may cause confusion for the team. why not add your challenge to the body of the existing solutions folder and place your test case into the existing test folder?

2024-12-29 22:47 UTC, Elocodes requested changes

2024-12-29 22:47 UTC, Elocodes commented on README.md
The general group repository Readme.md should explain the entire team project not a specific challenge as you have done here. consider moving this to the notes folder

2024-12-29 22:47 UTC, Elocodes commented on src/simple_interest_calculator.py
creating an added folder "src" for your specific challenge would disrupt team's project folder structure. consider moving the simple_interest_calculator.py file into the solutions folder and removing the "src" folder you created

2024-12-29 22:47 UTC, Elocodes commented on tests/test_simple_interest_calculator.py
To maintain same project folder structure for everyone, consider moving this file "test_simple_interest_calculator.py" into the already existing "tests" subfolder found in the solutions folder

2024-12-29 22:47 UTC, Elocodes commented on tests/test_simple_interest_calculator.py
Your unit tests are missing docstrings. Please note that comments in python are not the same as docstrings

2024-12-31 09:11 UTC, Mustafa-Mangal commented on README.md
Hi
I recently reorganized my project files for better clarity. The source files were moved from the Src folder to the Solutions folder, while the test files were relocated to the Tests folder. Additionally, the README file was moved to the Tests folder and renamed to reflect the task name.

2024-12-31 09:12 UTC, Mustafa-Mangal commented on src/simple_interest_calculator.py
Point it and moved the files to the designated folders

2024-12-31 09:15 UTC, Mustafa-Mangal commented on tests/test_simple_interest_calculator.py
Agree and done

2024-12-31 11:40 UTC, Mustafa-Mangal reviewed
Resolved the suggested changes

2024-12-31 11:40 UTC, Mustafa-Mangal commented on tests/test_simple_interest_calculator.py
Resolved

2024-12-31 12:35 UTC, Mustafa-Mangal commented on collaboration/README.md
> -<summary> What we do if that trust is broken  </summary>
The formatting was updated to replace `<details>` and `<summary>` HTML tags with Markdown headings and lists. This ensures compliance with Markdown linting rules and improves compatibility across different Markdown parsers.

2024-12-31 12:36 UTC, Mustafa-Mangal commented on collaboration/README.md
> -  </summary>
The formatting was updated to replace `<details>` and `<summary>` HTML tags with Markdown headings and lists. This ensures compliance with Markdown linting rules and improves compatibility across different Markdown parsers.

2024-12-31 12:37 UTC, Mustafa-Mangal reviewed
The formatting was updated to replace `<details>` and `<summary>` HTML tags with Markdown headings and lists. This ensures compliance with Markdown linting rules and improves compatibility across different Markdown parsers.

2024-12-31 12:37 UTC, Mustafa-Mangal commented on collaboration/README.md
> -  </summary>
# Explanation for Formatting Changes

The formatting was updated to replace `<details>` and `<summary>` HTML tags with Markdown headings and lists. This ensures compliance with Markdown linting rules and improves compatibility across different Markdown parsers.

2025-01-02 15:11 UTC, Elocodes approved these changes

2025-01-02 15:15 UTC, merged