Taiwo learning goals
MIT-Emerging-Talent/ET6-foundations-group-11 pull request #7
Opened 2024-12-30 00:17 UTC by Nate004

I wrote my personal learning goal to be reviewed by the team

2024-12-30 12:59 UTC, Elocodes requested changes

2024-12-30 12:59 UTC, Elocodes commented on .vscode/settings.json
what file did you work on?

2025-01-02 08:04 UTC, Shaifta commented
Great, there is a problem in formatting. it would be better to solve it.

2025-01-02 15:57 UTC, Nate004 commented on .vscode/settings.json
Something must have gone wrong, I'll create another request

2025-01-02 16:04 UTC, Nate004 commented on .vscode/settings.json
I worked on this file: [https://github.com/MIT-Emerging-Talent/ET6-foundations-group-11/pull/7/commits/6980f36ae9c543f08a5bd2cbbf2298d8b2d6983b](url)

2025-01-02 16:13 UTC, closed without merging